### ISSUE TITLE
chore/craco 적용

### ISSUE THREAD

**Issue by violet9503** [prgrms-web-devcourse/Team-10jo-10wonmoa-FE#8]
# 목표: 

# 구현사항
- [x] craco 적용을 통한 절대경로 지정
- [x] emotion 설치

**Comment by sa02045** [comment]
"@pages" -> "@/pages"로 수정할수 있을까요?

왜냐하면 `'@tanstack/react-query'`처럼 `@~` 시작하게되는 외부라이브러리와 구별이 가지않아
elinst가 import문 정렬할때 오류가 발생하는 것 같습니다.
